name: Diffblue Cover
description: Runs Diffblue Cover to automatically write and maintain Java unit tests.
author: Diffblue
inputs:
  license-key:
    required: true
    description: The license key provided in your welcome email or provided by your organization.
  access-token:
    required: true
    description: The access token used to push commits and call GitHub APIs.
  args:
    required: false
    description: The Diffblue Cover command line arguments. 
    default: >-
      ci
      activate
      validate
      create
  working-directory:
    required: false
    description: The working directory to pass to `dcover` comamnds that accept a `--working-directory` argument.
    default: .
runs:
  using: composite
  steps:
    - name: Install
      uses: ./install/
    - name: Execute
      shell: bash
      env:
        DIFFBLUE_LICENSE_KEY: ${{ inputs.license-key }}
        DIFFBLUE_WORKING_DIRECTORY: ${{ inputs.working-directory }} 
        DIFFBLUE_ACCESS_TOKEN: ${{ inputs.access-token }}
      working-directory: ${{ inputs.working-directory }}
      run: |
        pwd
        env | sort
        dcover ${{ inputs.args }}
