name: Diffblue Cover
description:
  Runs Diffblue Cover to automatically write and maintain Java unit tests.
  Variations of the action are available using various supported JDK versions.
  This variation uses JDK21.
author: Diffblue
branding:
  icon: check-circle
  color: blue
inputs:
  license-key:
    required: true
    description:
      The license key provided in your welcome email or provided by your organization.
      Alternatively obtain a free trial key from https://www.diffblue.com/try-cover/github.
  access-token:
    required: true
    description:
      The access token used to push commits and call GitHub APIs.

      Must have access to the project with at least Write role, and scopes
      including code, commit-statuses, pull-requests, workflows and actions.
  args:
    required: false
    description:
      The Diffblue Cover commands and options to use.
    default: >-
      ci
      activate
      build
      validate
      create
  working-directory:
    required: false
    description:
      Working directory where the project can be found, if not at the root.
    default: .
runs:
  using: docker
  image: Dockerfile
  env:
    DIFFBLUE_LICENSE_KEY: ${{ inputs.license-key }}
    DIFFBLUE_WORKING_DIRECTORY: ${{ inputs.working-directory }} 
    DIFFBLUE_ACCESS_TOKEN: ${{ inputs.access-token }}
