name: Diffblue Cover (install)
description: Component action for installing Diffblue Cover, used for custom workflows in complex projects.
author: Diffblue
runs:
  using: node16
  main: ../dist/install/index.js
