name: "Test: Custom Project"

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

# Avoid running the same workflow on the same branch concurrently
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:

  Test:
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [windows-latest]
        
    steps:

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          # The default GITHUB_TOKEN doesn't have the necessary permissions
          # so a custom token should be used here with sufficient access.
          token: ${{ secrets.DIFFBLUE_TOKEN }}
          # By default the merge commit is checked out, but here we want
          # the HEAD SHA in preparation for adding commits to the branch.
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Prepare Git Author
        # Diffblue Cover requires author name and email to be configured.
        # This allows adding new commits, and detecting previous automated commits.
        run: |
          git config user.name "Diffblue CI"
          git config user.email "db-ci-platform@diffblue.com"

      - name: Prepare Git Patch
        # Adding commits to the pull requst requires an author name and email address.
        if: github.event_name == 'pull_request'
        run: |
          mkdir .diffblue
          git fetch origin ${{ github.event.pull_request.base.ref }} --depth 100
          git fetch origin ${{ github.event.pull_request.head.ref }} --depth 100
          git diff --merge-base origin/${{ github.base_ref }} > .diffblue/cover-github-action.diff

      - name: Diffblue Cover (install)
        uses: ./install/
        env:
          GITHUB_TOKEN: ${{ secrets.DIFFBLUE_TOKEN }}
          JVM_ARGS: -Xmx4096m
        with:
          # Add a differentiator based on the matrix
          topic-id-differentiator: ${{ matrix.os }}

      - name: Diffblue Cover (activate)
        uses: ./activate/
        env:
          GITHUB_TOKEN: ${{ secrets.DIFFBLUE_TOKEN }}
          JVM_ARGS: -Xmx4096m
        with:
          # License key used to activate the installation
          license-key: ${{ secrets.DIFFBLUE_LICENSE_KEY }}
          # Add a differentiator based on the matrix
          topic-id-differentiator: ${{ matrix.os }}
      
      - name: Gradle Build
        working-directory: ./test/gradle-project
        run: ./gradlew --console plain build

      - name: Diffblue Cover (clean)
        uses: ./clean/
        env:
          GITHUB_TOKEN: ${{ secrets.DIFFBLUE_TOKEN }}
          JVM_ARGS: -Xmx4096m
        with:
          # Integration test project lives in a subdir
          working-directory: ./test/gradle-project
          # Add a differentiator based on the matrix
          topic-id-differentiator: ${{ matrix.os }}

      - name: Diffblue Cover (validate)
        uses: ./validate/
        env:
          GITHUB_TOKEN: ${{ secrets.DIFFBLUE_TOKEN }}
          JVM_ARGS: -Xmx4096m
        with:
          # Integration test project lives in a subdir
          working-directory: ./test/gradle-project
          # Add a differentiator based on the matrix
          topic-id-differentiator: ${{ matrix.os }}

      - name: Diffblue Cover (create)
        uses: ./create/
        env:
          GITHUB_TOKEN: ${{ secrets.DIFFBLUE_TOKEN }}
          JVM_ARGS: -Xmx4096m
        with:
          # Integration test project lives in a subdir
          working-directory: ./test/gradle-project
          # A patch file representing the pull request changes
          patch: .diffblue/cover-github-action.diff
          # Add a differentiator based on the matrix
          topic-id-differentiator: ${{ matrix.os }}
      
      - name: Git Push
        if: ${{ github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' }}
        run: git push origin HEAD:${{ github.event.pull_request.head.ref }}
